export const CREATE_CLIENT = 'CREATE_CLIENT';
export const CREATE_CLIENT_LEAD = 'CREATE_CLIENT_LEAD';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const FETCH_INTERESTS = 'FETCH_INTERESTS'